### ISSUE TITLE
Option to show pie chart in search

### ISSUE THREAD

**Issue by FelixSFD** [ArtOfCode-/Sentinel#1]
It would be great, if there was an option to show a pie chart, when searching for a phrase.

<img width="482" alt="bildschirmfoto 2017-01-09 um 16 59 24" src="https://cloud.githubusercontent.com/assets/2721240/21772878/52739ff8-d68d-11e6-9980-6de3fc7663cb.png">

When I'm about to blacklist or whitelist a phrase in Natty, I use the search to check if it throws many tps or fps. A pie chart would make this even easier.

**Comment by FelixSFD** [comment]
The search is not working anymore: http://sentinel.erwaysoftware.com/search

>We're sorry, but something went wrong. If you are the application owner check the logs for more information.

**Comment by Undo1** [comment]
Art already fixed; I'm just slow on the deploy.

**Comment by FelixSFD** [comment]
Okay :-D No problem
