### ISSUE TITLE
Smileys aren't supported on Sentinel

### ISSUE THREAD

**Issue by Bhargav-Rao** [ArtOfCode-/Sentinel#2]
This post contained a smiley at the end. Sentinel returned a 500 ISE error when the body of the post was sent. 

http://stackoverflow.com/questions/15500560/html-to-pdf-using-htmlworker-in-java/41590032#41590032

(FMS Link - http://51.254.218.90:8000/NATO/41590067.html) 

Searches with emojis are also not supported. 

http://sentinel.erwaysoftware.com/search?utf8=✓&q=😂&commit=Search

Returns an error as well.

**Comment by ArtOfCode-** [comment]
^ Sentinel runs on UTF8. If a character fits in that, fine - if it requires UTF8-MBx, as many emoji do, it's not gonna work. It's also not worth converting the whole thing to UTF8-MBx for a minority of posts.

Better to replace these on the client side, as you suggested.
