### ISSUE TITLE
Implement a 'score' search field

### ISSUE THREAD

**Issue by Tunaki** [ArtOfCode-/Sentinel#4]
[The current search feature](http://sentinel.erwaysoftware.com/search) enables to search in the title, body or username. It would be nice to provide an additional field to search posts by score (e.g. having a score greater or smaller than a given value). When the field is left empty, the system would return all posts matching the other criteria.

**Comment by ArtOfCode-** [comment]
I thought this was an MS FR for a moment and was about to close it... that's what I get for not reading.
