### ISSUE TITLE
Values in the pie charts differ from the values in the list

### ISSUE THREAD

**Issue by FelixSFD** [ArtOfCode-/Sentinel#7]
For example on the page of the "One line only" reason: https://sentinel.erwaysoftware.com/reasons/4

<img width="742" alt="bildschirmfoto 2017-02-10 um 18 44 47" src="https://cloud.githubusercontent.com/assets/2721240/22837528/519fd70c-efc1-11e6-8059-517424b48fa2.png">

**Comment by ArtOfCode-** [comment]
gremlins
