### ISSUE TITLE
Posts don't disappear after giving feedback in review

### ISSUE THREAD

**Issue by Fortunate-MAN** [ArtOfCode-/Sentinel#8]
The same thing which happened in MS: https://github.com/Charcoal-SE/metasmoke/issues/131

**Comment by ArtOfCode-** [comment]
Refresh the page. The JS doesn't work on first page load for some reason (I blame Turbolinks), but reloading fixes it. I'm looking for a fix, but for now this is a workaround.

**Comment by Undo1** [comment]
That may have fixed the issue; but I'll wait for others to repro before closing.

**Comment by Fortunate-MAN** [comment]
@Undo1 yeah, that seemed to have worked!
